# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Charge automatiquement tous les services dans src/
    App\:
        resource: '../src/'

    # EXCEPTION : ton extension API Platform (optionnel mais propre)
    App\Doctrine\CurrentUserExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }
            - { name: api_platform.doctrine.orm.query_extension.item }